package framework.graphics.opengl.bufferObjects;

import org.lwjgl.opengl.GL30;

/**
 * Created by Will on 1/25/2015.
 */
public enum AttachmentType {

    DEPTH_ATTACHMENT(GL30.GL_DEPTH_ATTACHMENT),
    STENCIL_ATTACHMENT(GL30.GL_STENCIL_ATTACHMENT),
    COLOR_ATTACHMENT0(GL30.GL_COLOR_ATTACHMENT0),
    COLOR_ATTACHMENT1(GL30.GL_COLOR_ATTACHMENT1),
    COLOR_ATTACHMENT2(GL30.GL_COLOR_ATTACHMENT2),
    COLOR_ATTACHMENT3(GL30.GL_COLOR_ATTACHMENT3),
    COLOR_ATTACHMENT4(GL30.GL_COLOR_ATTACHMENT4),
    COLOR_ATTACHMENT5(GL30.GL_COLOR_ATTACHMENT5),
    COLOR_ATTACHMENT6(GL30.GL_COLOR_ATTACHMENT6),
    COLOR_ATTACHMENT7(GL30.GL_COLOR_ATTACHMENT7),
    COLOR_ATTACHMENT8(GL30.GL_COLOR_ATTACHMENT8),
    COLOR_ATTACHMENT9(GL30.GL_COLOR_ATTACHMENT9);

    public final int ID;

    private AttachmentType(final int id) {

        this.ID = id;
    }
}
